// Generated by Google Gemini

sequence {
    stage idle {
        // Line order dictates priority. Disable is evaluated first.
        disable_button > 0          => set_disable
        position_control_button > 0 => set_position
        speed_control_button > 0    => set_speed
    }

    stage set_disable {
        0 -> motor_cmd
        
        // Wait until the button is released before returning to idle
        disable_button == 0 => idle
    }

    stage set_position {
        1 -> motor_cmd
        
        // Safety interlock: If the disable button is pushed while we 
        // are in position mode, jump immediately to the disable stage.
        disable_button > 0 => set_disable
        
        // Otherwise, go back to idle when released.
        position_control_button == 0 => idle
    }

    stage set_speed {
        2 -> motor_cmd
        
        disable_button > 0 => set_disable
        speed_control_button == 0 => idle
    }
}